@startuml классы развитие
class Книга {
  - название: Строка
  - автор: Строка
  - залог: Вещественное
  - стоимость проката: Вещественное
  - жанр: Строка

  + добавить(): void
  + изменить(): void
  + удалить(): void
}

class Читатель {
  - фамилия: Строка
  - имя: Строка
  - отчество: Строка
  - адрес: Строка
  - телефон: Строка

  + зарегистрировать(): void
  + изменить(): void
  + удалить(): void
}

class Транзакция {
  - книга: Книга
  - читатель: Читатель
  - дата Выдачи: Дата
  - дата Возврата: Дата

  + проверить Наличие(): void
  + оформить Заказ(): void
  + оплатить Залог(): void
  + рассчитать Штраф(): void
  + вернуть Залог(): void
}

class Аренда {
  - книга: Книга
  - длительность Проката: Целое
  - стоимость Проката: Вещественное
  - штраф: Вещественное
  - скидка: Вещественное

  + установить Стоимость Проката(): void
  + применить Штраф За Повреждения(): void
  + применить Скидки(): void
}

Книга "1" -- "0..*" Транзакция
Читатель "1" -- "0..*" Транзакция
Книга "1" -- "0..*" Аренда
@enduml
