@startuml деятельность развитие
|Читатель|
start
:Выбрать Книгу;
if (Доступна?) then (да)
  :Взять Книгу;
  :Оплатить Залог;
  :Записать Транзакцию;
else (нет)
  :Сделать Заказ;
  :Уведомить о наличии;
endif
end

|Библиотекарь|
start
:Установить Стоимость проката;
:Применить Штраф За Повреждения;
:Применить Скидки;
end
@enduml
