@startuml классы начало
class Книга {
  - название: Строка
  - автор: Строка
  - залог: Вещественное
  - стоимость проката: Вещественное
  - жанр: Строка
}

class Читатель {
  - фамилия: Строка
  - имя: Строка
  - отчество: Строка
  - адрес: Строка
  - телефон: Строка
}

class Транзакция {
  - книга: Книга
  - читатель: Читатель
  - дата Выдачи: Дата
  - дата Возврата: Дата
}

Книга "1" -- "0..*" Транзакция
Читатель "1" -- "0..*" Транзакция
@enduml
