@startuml деятельность начало
|Читатель|
start
:Выбрать Книгу;
if (Доступна?) then (да)
  :Взять Книгу;
  :Оплатить Залог;
  :Записать Транзакцию;
else (нет)
  :Сделать Заказ;
  :Уведомить о наличии;
endif
end
@enduml
