@startuml прецеденты начало
left to right direction
skinparam packageStyle rectangle
actor Библиотекарь
actor Читатель

rectangle БиблиотечнаяСистема {
  Библиотекарь -- (Управление Книгами)
  Библиотекарь -- (Управление Читателями)
  Читатель -- (Взять Книгу)
  Читатель -- (Вернуть Книгу)
}

(Управление Книгами) --> (Добавить Книгу)
(Управление Книгами) --> (Изменить Книгу)
(Управление Книгами) --> (Удалить Книгу)

(Управление Читателями) --> (Зарегистрировать Читателя)
(Управление Читателями) --> (Изменить Читателя)
(Управление Читателями) --> (Удалить Читателя)

(Взять Книгу) --> (Проверить Наличие)
(Взять Книгу) --> (Оформить Заказ)
(Взять Книгу) --> (Оплатить Залог)

(Вернуть Книгу) --> (Рассчитать Штраф)
(Вернуть Книгу) --> (Вернуть Залог)
@enduml
