INSERT INTO s_emp
VALUES
(1,'Velasquez','Carmen','cvelasqu',to_date('3.03.1990','dd.mm.yyyy'),NULL,NULL,'President',32,2550,NULL)
/
INSERT INTO s_emp
VALUES
(2,'Ngao','LaDoris','lngao',to_date('8.03.1990','dd.mm.yyyy'),NULL,1,'VP, Operations',54,1450,NULL)
/
INSERT INTO s_emp
VALUES
(3,'Nagayamn','Midori','mnagayam',to_date('17.06.1991','dd.mm.yyyy'),NULL,1,'VP, Sales',31,1400,NULL)
/
INSERT INTO s_emp
VALUES
(4,'Quick-To-See','Mark','mquickto',to_date('7.04.1990','dd.mm.yyyy'),NULL,1,'VP, Finance',10,1450,NULL)
/
INSERT INTO s_emp
VALUES
(5,'Ropeburn','Audry','aropebur',to_date('4.03.1990','dd.mm.yyyy'),NULL,1,'VP, Administration',50,1550,NULL)
/
INSERT INTO s_emp
VALUES
(6,'Urguhart','Molly','murguhar',to_date('18.01.1991','dd.mm.yyyy'),NULL,2,'Warehouse Manager',41,1200,NULL)
/
INSERT INTO s_emp
VALUES
(7,'Menchu','Robertn','rmenchu',to_date('14.05.1990','dd.mm.yyyy'),NULL,2,'Warehouse Manager',42,1250,NULL)
/
INSERT INTO s_emp
VALUES
(8,'Biri','Ben','bbiri',to_date('7.04.1990','dd.mm.yyyy'),NULL,2,'Warehouse Manager',43,1100,NULL)
/
INSERT INTO s_emp
VALUES
(9,'Catchpole','Antoinette','acatchpo',to_date('9.02.1992','dd.mm.yyyy'),NULL,2,'Warehouse Manager',44,1300,NULL)
/
INSERT INTO s_emp
VALUES
(10,'Havel','Marta','mhavel',to_date('27.02.1991','dd.mm.yyyy'),NULL,2,'Warehouse Manager',45,1307,NULL)
/
INSERT INTO s_emp
VALUES
(11,'Magee','Colin','cmagee',to_date('14.05.1990','dd.mm.yyyy'),NULL,3,'Sales Representative',31,1400,10)
/
INSERT INTO s_emp
VALUES
(13,'Sedeghi','Yasmin','ysedeghi',to_date('18.02.1991','dd.mm.yyyy'),NULL,3,'Sales Representative',33,1515,10)
/
INSERT INTO s_emp
VALUES
(14,'Nguyen','Mai','mnguyen',to_date('22.01.1992','dd.mm.yyyy'),NULL,3,'Sales Representative',34,1525,15)
/
INSERT INTO s_emp
VALUES
(16,'Maduro','Elena','emaduro',to_date('7.02.1992','dd.mm.yyyy'),NULL,6,'Stock Clerk',41,1400,NULL)
/
INSERT INTO s_emp
VALUES
(17,'Smith','George','gsmith',to_date('8.03.1990','dd.mm.yyyy'),NULL,6,'Stock Clerk',41,940,NULL)
/
INSERT INTO s_emp
VALUES
(18,'Nozaki','Akira','anozaki',to_date('9.02.1991','dd.mm.yyyy'),NULL,7,'Stock Clerk',42,1200,NULL)
/
INSERT INTO s_emp
VALUES
(19,'Patel','Vikram','vpatel',to_date('6.08.1991','dd.mm.yyyy'),NULL,7,'Stock Clerk',42,795,NULL)
/
INSERT INTO s_emp
VALUES
(20,'Newman','Chad','cnewman',to_date('21.07.1991','dd.mm.yyyy'),NULL,8,'Stock Clerk',43,750,NULL)
/
INSERT INTO s_emp
VALUES
(21,'Markarian','Alexander','amarkari',to_date('26.05.1991','dd.mm.yyyy'),NULL,8,'Stock Clerk',43,850,NULL)
/
INSERT INTO s_emp
VALUES
(22,'Chang','Eddie','echang',to_date('30.11.1990','dd.mm.yyyy'),NULL,9,'Stock Clerk',44,800,NULL)
/
INSERT INTO s_emp
VALUES
(23,'Patel','Radha','rpatel',to_date('17.10.1990','dd.mm.yyyy'),NULL,9,'Stock Clerk',34,795,NULL)
/
INSERT INTO s_emp
VALUES
(24,'Dancs','Bela','bdancs',to_date('17.03.1991','dd.mm.yyyy'),NULL,10,'Stock Clerk',45,860,NULL)
/
INSERT INTO s_emp
VALUES
(25,'Schwart,z','Sylvie','sschwart',to_date('9.05.1991','dd.mm.yyyy'),NULL,10,'Stock Clerk',45,1100,NULL)
/
