INSERT INTO s_ord
VALUES
(100,204,to_date('31.08.1992','dd.mm.yyyy'),to_date('10.09.1992','dd.mm.yyyy'),11,601100,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(102,206,to_date('1.09.1992','dd.mm.yyyy'),to_date('8.09.1992','dd.mm.yyyy'),11,8335,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(103,208,to_date('2.09.1992','dd.mm.yyyy'),to_date('22.09.1992','dd.mm.yyyy'),11,377,'CASH',NULL)
/
INSERT INTO s_ord
VALUES
(104,208,to_date('3.09.1992','dd.mm.yyyy'),to_date('23.09.1992','dd.mm.yyyy'),21,32430,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(106,210,to_date('7.09.1992','dd.mm.yyyy'),to_date('15.09.1992','dd.mm.yyyy'),21,15634,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(107,211,to_date('7.09.1992','dd.mm.yyyy'),to_date('21.09.1992','dd.mm.yyyy'),21,142171,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(108,212,to_date('7.09.1992','dd.mm.yyyy'),to_date('10.09.1992','dd.mm.yyyy'),13,149570,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(109,213,to_date('8.09.1992','dd.mm.yyyy'),to_date('28.09.1992','dd.mm.yyyy'),11,1020935,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(111,204,to_date('9.09.1992','dd.mm.yyyy'),to_date('21.09.1992','dd.mm.yyyy'),11,2770,'CASH',NULL)
/
INSERT INTO s_ord
VALUES
(97,201,to_date('28.08.1992','dd.mm.yyyy'),to_date('17.09.1992','dd.mm.yyyy'),11,84000,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(98,202,to_date('31.08.1992','dd.mm.yyyy'),to_date('10.09.1992','dd.mm.yyyy'),14,595,'CASH',NULL)
/
INSERT INTO s_ord
VALUES
(99,203,to_date('31.08.1992','dd.mm.yyyy'),to_date('18.09.1992','dd.mm.yyyy'),14,7707,'CREDIT',NULL)
/
INSERT INTO s_ord
VALUES
(112,210,to_date('31.08.1992','dd.mm.yyyy'),to_date('10.09.1992','dd.mm.yyyy'),21,550,'CREDIT',NULL)
/
